const PricesActionTypes = {
    GET_CLIENT_PRICES_START:"GET_CLIENT_PRICES_START",
    GET_CLIENT_PRICES_SUCCESS:"GET_CLIENT_PRICES_SUCCESS",
    GET_CLIENT_PRICES_FAILED:"GET_CLIENT_PRICES_FAILED",
    REMOVE_OFFER_START:"REMOVE_OFFER_START",
    REMOVE_OFFER_STATUS:"REMOVE_OFFER_STATUS",
    UPDATE_OFFER_LIST:"UPDATE_OFFER_LIST",
    REMOVE_OFFER_LIST:"REMOVE_OFFER_LIST",
    UPDATE_OFFERS_START:"UPDATE_OFFERS_START",
    UPDATE_OFFERS_STATUS:"UPDATE_OFFERS_STATUS",
    CLEAR_OFFERS_LIST:"CLEAR_OFFERS_LIST"
}

export default PricesActionTypes