export const RestrictionActionTypes = {
    FETCH_RESTR_START:"FETCH_RESTR_START",
    FETCH_RESTR_SUCCESS:"FETCH_RESTR_SUCCESS",
    FETCH_RESTR_FAILED:"FETCH_RESTR_FAILED",
    GET_PRODUCT_STOCK:"GET_PRODUCT_STOCK",
    PRODUCT_STOCK_SUCCESS:"PRODUCT_STOCK_SUCCESS",
    CLEAR_PRODUCT_STOCK:"CLEAR_PRODUCT_STOCK",
    SET_REASON:"SET_REASON",
    SET_START_TIME:"SET_START_TIME",
    SET_END_TIME:"SET_END_TIME",
    SET_NEW_REST:"SET_NEW_REST",
    CLEAR_NEW_REST:"CLEAR_NEW_REST",
    SAVE_QOUTA:"SAVE_QOUTA",
    SAVE_QOUTA_SUCCESS:"SAVE_QOUTA_SUCCESS",
    CANCEL_RESTRICTION:"CANCEL_RESTRICTION"
}