const VoucherActionTypes = {
    FETCH_BATCHLIST_START:"FETCH_BATCHLIST_START",
    FETCH_BATCHLIST_SUCCESS:"FETCH_BATCHLIST_SUCCESS",
    FETCH_BATCHLIST_FAILED:"FETCH_BATCHLIST_FAILED",
    SET_EDIT_BATCH:"SET_EDIT_BATCH",
    UPLOAD_VOUCHER_START:"UPLOAD_VOUCHER_START",
    UPLOAD_VOUCHER_ERRORS:"UPLOAD_VOUCHER_ERRORS",
    GET_PRODUCT_ID:"GET_PRODUCT_ID",
    PRODUCT_ID_SUCCESS:"PRODUCT_ID_SUCCESS",
    CONFIRM_UPLOAD:"CONFIRM_UPLOAD",
    CONFIRM_UPLOAD_STATUS:"CONFIRM_UPLOAD_STATUS",
    SET_CURRENT_BATCH:"SET_CURRENT_BATCH",
    FETCH_VOUCHERS_START:"FETCH_VOUCHERS_START",
    FETCH_VOUCHERS_SUCCESS:"FETCH_VOUCHERS_SUCCESS",
    FETCH_VOUCHERS_FAILED:"FETCH_VOUCHERS_FAILED",
    TOGGLE_DELETE_VOUCHER:"TOGGLE_DELETE_VOUCHER",
    DELETE_VOUCHERS_START:"DELETE_VOUCHERS_START",
    DELETE_VOUCHERS_SUCCESS:"DELETE_VOUCHERS_SUCCESS",
    DELETE_VOUCHERS_FAILED:"DELETE_VOUCHERS_FAILED",
    CLEAR_VOUCHER_ERRORS:"CLEAR_VOUCHER_ERRORS",
    CLEAR_PRODUCT_ID:"CLEAR_PRODUCT_ID",
    UPDATE_BATCH_ACTIVATION:"UPDATE_BATCH_ACTIVATION",
    CANCEL_BATCH:"CANCEL_BATCH",
    EDIT_BATCH:"EDIT_BATCH",
    EDIT_BATCH_STATUS:"EDIT_BATCH_STATUS"
}

export default VoucherActionTypes