const ClientActionTypes = {
    FETCH_START_ASYNC:"FETCH_START_ASYNC",
    FETCH_SUCCESSFULL_ASYNC:"FETCH_SUCCESSFULL_ASYNC",
    FETCH_FAILED_ASYNC:"FETCH_FAILED_ASYNC",
    GET_PERMS:"GET_PERMS",
    GET_PERMS_SUCCESS:"GET_PERMS_SUCCESS",
    UPDATE_START_ASYNC:"UPDATE_START_ASYNC",
    UPDATE_SUCCESSFULL_ASYNC:"UPDATE_SUCCESSFULL_ASYNC",
    UPDATE_FAILED_ASYNC:"UPDATE_FAILED_ASYNC",
    UPDATE_WALLET_START:"UPDATE_WALLET_START",
    UPDATE_PAYMENT_START:"UPDATE_PAYMENT_START",
    CREATE_CLIENT:"CREATE_CLIENT",
    CREATE_CLIENT_STATUS:"CREATE_CLIENT_STATUS",
    EDIT_USER:"EDIT_USER",
    EDIT_CLIENT_STATUS:"EDIT_CLIENT_STATUS"
}

export default ClientActionTypes