const ClientActionTypes = {
    FETCH_START_ASYNC:"FETCH_START_ASYNC",
    FETCH_SUCCESSFULL_ASYNC:"FETCH_SUCCESSFULL_ASYNC",
    FETCH_FAILED_ASYNC:"FETCH_FAILED_ASYNC",
    UPDATE_START_ASYNC:"UPDATE_START_ASYNC",
    UPDATE_SUCCESSFULL_ASYNC:"UPDATE_SUCCESSFULL_ASYNC",
    UPDATE_FAILED_ASYNC:"UPDATE_FAILED_ASYNC",
    UPDATE_WALLET_START:"UPDATE_WALLET_START",
    UPDATE_PAYMENT_START:"UPDATE_PAYMENT_START"
}

export default ClientActionTypes