export const VendorActionTypes = {
    GET_VENDORS:"GET_VENDORS",
    GET_VENDORS_SUCCESS:"GET_VENDORS_SUCCESS",
    GET_VENDORS_STATUS:"GET_VENDORS_STATUS",
    CREATE_VENDOR:"CREATE_VENDOR",
    CREATE_VENDOR_STATUS:"CREATE_VENDOR_STATUS",
    EDIT_VENDOR:"EDIT_VENDOR",
    EDIT_VENDOR_STATUS:"EDIT_VENDOR_STATUS"
}