const StaffActionTypes = {
    FETCH_STAFF_START_ASYNC:"FETCH_STAFF_START_ASYNC",
    FETCH_STAFF_SUCCESSFULL_ASYNC:"FETCH_STAFF_SUCCESSFULL_ASYNC",
    FETCH_STAFF_FAILED_ASYNC:"FETCH_STAFF_FAILED_ASYNC",
    UPDATE_STAFF_INFO:"UPDATE_STAFF_INFO",
    CREATE_STAFF:"CREATE_STAFF"
}

export default StaffActionTypes