const StaffActionTypes = {
    FETCH_STAFF_START_ASYNC:"FETCH_STAFF_START_ASYNC",
    FETCH_STAFF_SUCCESSFULL_ASYNC:"FETCH_STAFF_SUCCESSFULL_ASYNC",
    FETCH_STAFF_FAILED_ASYNC:"FETCH_STAFF_FAILED_ASYNC",
    UPDATE_STAFF_INFO:"UPDATE_STAFF_INFO",
    CREATE_STAFF:"CREATE_STAFF",
    STAFF_CREATED:"STAFF_CREATED",
    STAFF_UPDATED:"STAFF_UPDATED"
}

export default StaffActionTypes