const StaffActionTypes = {
    FETCH_STAFF_START_ASYNC:"FETCH_STAFF_START_ASYNC",
    FETCH_STAFF_SUCCESSFULL_ASYNC:"FETCH_STAFF_SUCCESSFULL_ASYNC",
    FETCH_STAFF_FAILED_ASYNC:"FETCH_STAFF_FAILED_ASYNC"
}

export default StaffActionTypes